//! End-to-end tests: they run the real binary against throwaway documents.

use std::path::Path;
use std::process::{Command, Output};

use tempfile::TempDir;

/// A document with one root, a shared chunk, a concatenated chunk and indentation.
const DOC: &str = "\
= Demo

```py
<<imports>>
<<body>>
``` <main.py>

```py
import sys
``` <imports>

```py
print('one')
``` <body>

```py
print('two')
``` <body>
";

fn lp(dir: &Path, args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_lp"))
        .args(args)
        .current_dir(dir)
        .output()
        .expect("run lp")
}

fn write(dir: &Path, name: &str, contents: &str) {
    std::fs::write(dir.join(name), contents).expect("write fixture");
}

fn stdout(output: &Output) -> String {
    String::from_utf8_lossy(&output.stdout).to_string()
}

fn stderr(output: &Output) -> String {
    String::from_utf8_lossy(&output.stderr).to_string()
}

fn line_of(text: &str, needle: &str) -> usize {
    text.lines()
        .position(|line| line.contains(needle))
        .expect("needle")
        + 1
}

fn project(doc: &str) -> (TempDir, std::path::PathBuf) {
    let dir = TempDir::new().expect("temp dir");
    write(dir.path(), "demo.typ", doc);
    let path = dir.path().to_path_buf();
    (dir, path)
}

#[test]
fn tangle_writes_files_with_concat_and_indentation() {
    let (_guard, dir) = project(DOC);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(output.status.success(), "{}", stderr(&output));

    let main = std::fs::read_to_string(dir.join("out/main.py")).expect("main.py");
    assert_eq!(main, "import sys\nprint('one')\nprint('two')\n");
}

#[test]
fn tangle_records_where_every_line_came_from() {
    let (_guard, dir) = project(DOC);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let map: serde_json::Value =
        serde_json::from_str(&std::fs::read_to_string(dir.join("out/.lpmap.json")).expect("map"))
            .expect("json");
    let lines = map["files"]["main.py"]["lines"].as_array().expect("lines");
    let sources = map["files"]["main.py"]["sources"]
        .as_array()
        .expect("sources");
    assert_eq!(sources, &[serde_json::json!("demo.typ")]);

    // Output line 3 comes from the *second* <body> block, not from the reference;
    // the third element names which source file that line lives in.
    let expected = line_of(DOC, "print('two')");
    assert_eq!(lines[2], serde_json::json!([3, expected, 0]));
}

#[test]
fn indentation_follows_the_reference_site() {
    let doc = "```py\nif True:\n    <<body>>\n``` <main.py>\n\n```py\nprint(1)\n``` <body>\n";
    let (_guard, dir) = project(doc);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );
    let main = std::fs::read_to_string(dir.join("out/main.py")).expect("main.py");
    assert_eq!(main, "if True:\n    print(1)\n");
}

#[test]
fn typst_dedents_the_block_and_the_reference_adds_it_back() {
    // A chunk written inside a list item is indented in the document; Typst strips
    // that common indentation, so it tangles flush left and only the reference
    // site decides the indentation of the expansion.
    let doc = "- step one:\n\n  ```py\n  print(1)\n  print(2)\n  ``` <body>\n\n```py\nif x:\n    <<body>>\n``` <main.py>\n";
    let (_guard, dir) = project(doc);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(
        std::fs::read_to_string(dir.join("out/main.py")).expect("main"),
        "if x:\n    print(1)\n    print(2)\n"
    );
}

#[test]
fn the_map_follows_the_document_even_when_no_output_byte_changes() {
    let (_guard, dir) = project(DOC);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    // A line of prose above the chunks shifts every mapping and changes no
    // generated byte: the outputs stay untouched, but the map must not.
    let moved = format!("= Preamble\n\n{DOC}");
    std::fs::write(dir.join("demo.typ"), &moved).expect("rewrite doc");

    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert!(
        !stdout(&output).contains("wrote"),
        "outputs are unchanged: {}",
        stdout(&output)
    );

    let forward = lp(
        &dir,
        &["map", "--file", "main.py", "--line", "3", "--out", "out"],
    );
    assert!(forward.status.success(), "{}", stderr(&forward));
    let report = stdout(&forward);
    let expected = line_of(&moved, "print('two')");
    assert!(
        report.starts_with(&format!("demo.typ:{expected}")),
        "stale map: {report}"
    );
}

#[test]
fn a_document_of_fragments_is_fine_when_another_carries_the_roots() {
    // The woven document is split into chapters; the chunks live in one of them.
    // Only requiring roots per file would reject every chapter but the last.
    let chapter = "= Chapter one\n\nAll prose, no chunks.\n";
    let main = "= The program\n\n```py\nprint('hi')\n``` <main.py>\n";
    let dir = TempDir::new().expect("temp dir");
    std::fs::write(dir.path().join("chapter.typ"), chapter).expect("chapter");
    std::fs::write(dir.path().join("main.typ"), main).expect("main");
    let path = dir.path().to_path_buf();

    let output = lp(
        &path,
        &["tangle", "main.typ", "chapter.typ", "--out", "out"],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(
        std::fs::read_to_string(path.join("out/main.py")).expect("main"),
        "print('hi')\n"
    );

    // But a run with no roots anywhere is still an error.
    let only_fragments = lp(&path, &["tangle", "chapter.typ", "--out", "out2"]);
    assert!(!only_fragments.status.success());
    assert!(
        stderr(&only_fragments).contains("no root chunks"),
        "{}",
        stderr(&only_fragments)
    );
}

#[test]
fn maps_live_next_to_the_files_they_explain() {
    let doc = "```py\nprint('a')\n``` <a.py>\n\n```py\nprint('b')\n``` #label(\"src/b.py\")\n";
    let (_guard, dir) = project(doc);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let root: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join("out/.lpmap.json")).expect("root map"),
    )
    .expect("json");
    let nested: serde_json::Value = serde_json::from_str(
        &std::fs::read_to_string(dir.join("out/src/.lpmap.json")).expect("nested map"),
    )
    .expect("json");
    assert!(root["files"].get("a.py").is_some(), "{root}");
    assert!(
        root["files"].get("src/b.py").is_none(),
        "the root map must not index the subtree: {root}"
    );
    assert!(nested["files"].get("b.py").is_some(), "{nested}");

    // A path resolves against the most specific map; a bare name works when it
    // is unambiguous.
    for file in ["src/b.py", "b.py"] {
        let output = lp(
            &dir,
            &["map", "--file", file, "--line", "1", "--out", "out"],
        );
        assert!(output.status.success(), "{file}: {}", stderr(&output));
        assert_eq!(stdout(&output).lines().next(), Some("demo.typ:6"), "{file}");
    }

    // Reverse, with the directory spelled out.
    let reverse = lp(
        &dir,
        &["map", "--typ", "demo.typ", "--line", "6", "--out", "out"],
    );
    assert!(
        stdout(&reverse).contains("src/b.py:1"),
        "{}",
        stdout(&reverse)
    );
}

#[test]
fn an_ambiguous_file_name_is_an_error_not_a_guess() {
    let doc = "```py\nprint('a')\n``` #label(\"one/b.py\")\n\n```py\nprint('b')\n``` #label(\"two/b.py\")\n";
    let (_guard, dir) = project(doc);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let output = lp(
        &dir,
        &["map", "--file", "b.py", "--line", "1", "--out", "out"],
    );
    assert!(!output.status.success());
    assert!(
        stderr(&output).contains("which line map?"),
        "{}",
        stderr(&output)
    );

    let explicit = lp(
        &dir,
        &["map", "--file", "two/b.py", "--line", "1", "--out", "out"],
    );
    assert!(explicit.status.success(), "{}", stderr(&explicit));
}

#[test]
fn check_reports_drift_with_the_typ_line() {
    let (_guard, dir) = project(DOC);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let check = lp(&dir, &["tangle", "demo.typ", "--out", "out", "--check"]);
    assert!(
        check.status.success(),
        "clean run must succeed: {}",
        stderr(&check)
    );

    write(&dir.join("out"), "main.py", "hand edited\n");
    let drift = lp(&dir, &["tangle", "demo.typ", "--out", "out", "--check"]);
    assert!(!drift.status.success(), "drift must fail");
    let message = stderr(&drift);
    assert!(message.contains("STALE  main.py"), "{message}");
    // the first difference is line 1, which came from the <imports> chunk
    assert!(
        message.contains(&format!("demo.typ:{}", line_of(DOC, "import sys"))),
        "{message}"
    );

    // and tangling again fixes it
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out", "--check"])
            .status
            .success()
    );
}

#[test]
fn dangling_reference_points_at_the_reference_line() {
    let doc = "```py\n<<missing>>\n``` <main.py>\n";
    let (_guard, dir) = project(doc);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(!output.status.success());
    let message = stderr(&output);
    assert!(
        message.contains("chunk <<missing>> is not defined"),
        "{message}"
    );
    assert!(message.contains("demo.typ:2"), "{message}");
}

#[test]
fn cycle_is_reported() {
    let doc = "```py\n<<b>>\n``` <main.py>\n\n```py\n<<a>>\n``` <a>\n\n```py\n<<b>>\n``` <b>\n";
    let (_guard, dir) = project(doc);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(!output.status.success());
    assert!(
        stderr(&output).contains("cycle in chunks"),
        "{}",
        stderr(&output)
    );
}

#[test]
fn label_constructor_form_writes_nested_paths() {
    let doc = "```rust\nfn main() {}\n``` #label(\"src/main.rs\")\n";
    let (_guard, dir) = project(doc);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(
        std::fs::read_to_string(dir.join("out/src/main.rs")).expect("nested"),
        "fn main() {}\n"
    );
}

#[test]
fn unsafe_paths_are_rejected() {
    let doc = "```text\nx\n``` #label(\"../escape.txt\")\n";
    let (_guard, dir) = project(doc);
    let output = lp(&dir, &["tangle", "demo.typ", "--out", "out"]);
    assert!(!output.status.success());
    assert!(
        stderr(&output).contains("unsafe chunk name"),
        "{}",
        stderr(&output)
    );
}

#[test]
fn map_translates_a_generated_line_back_to_the_document() {
    let (_guard, dir) = project(DOC);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let output = lp(
        &dir,
        &["map", "--file", "main.py", "--line", "3", "--out", "out"],
    );
    assert!(output.status.success(), "{}", stderr(&output));
    assert_eq!(
        stdout(&output).lines().next(),
        Some(format!("demo.typ:{}", line_of(DOC, "print('two')")).as_str())
    );
}

#[test]
fn explain_rewrites_diagnostics_to_the_document() {
    let (_guard, dir) = project(DOC);
    assert!(
        lp(&dir, &["tangle", "demo.typ", "--out", "out"])
            .status
            .success()
    );

    let mut child = Command::new(env!("CARGO_BIN_EXE_lp"))
        .args(["explain", "--out", "out"])
        .current_dir(&dir)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::piped())
        .stderr(std::process::Stdio::piped())
        .spawn()
        .expect("spawn");

    use std::io::Write;
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(b"out/main.py:3:1: boom\n")
        .expect("write");
    let output = child.wait_with_output().expect("wait");

    assert!(stdout(&output).contains("out/main.py:3:1: boom"));
    let message = stderr(&output);
    assert!(
        message.contains(&format!("demo.typ:{}", line_of(DOC, "print('two')"))),
        "{message}"
    );
}

#[test]
fn list_reports_roots() {
    let (_guard, dir) = project(DOC);
    let output = lp(&dir, &["list", "demo.typ"]);
    assert!(output.status.success(), "{}", stderr(&output));
    let listed = stdout(&output);
    assert!(listed.contains("root  <main.py>"), "{listed}");
    assert!(listed.contains("outputs: <main.py>"), "{listed}");
}
