#import "../../lit/lit.typ": lit
#show: lit

#set page(width: 15cm, height: auto, margin: 2cm)
#set text(size: 10pt)

= A multi-file crate, written as one document

This document is a normal Typst file — `typst compile examples/demo/literate.typ`
renders it. It is also the only source of a small Rust crate: every chunk whose
label looks like a file name (`` `#label("src/lib.rs")` ``) becomes a real file when you run

```sh
lp tangle examples/demo/literate.typ --out examples/demo/build
```

Text like this never reaches the generated code. Chunks pull each other in with
`<<name>>`, in whatever order reads best.

== The manifest

The crate is its own workspace so the surrounding repository's `Cargo.toml`
does not claim it.

```toml
[package]
name = "lp-demo"
version = "0.0.0"
edition = "2024"

# `lp` output is standalone; keep it out of the parent workspace.
[workspace]
``` <Cargo.toml>

== A shared preamble

Both crate roots want the same banner comment at the top. It is not something
`lp` injects: the tool writes exactly the chunks you give it, nothing else. This
is just a chunk that two different root chunks happen to pull in — the same text
in two files, written once:

```rust
//! generated by lp from literate.typ — edit the document, not this file
``` <crate-preamble>

== The library

`` `<<math-items>>` `` sits inside a module, so its two chunks are indented by four
spaces on the way out:

```rust
<<crate-preamble>>

pub mod math {
    <<math-items>>
}
``` #label("src/lib.rs")

The module has two functions, written as two separate blocks that share the
label `<math-items>`. Tangling concatenates same-labelled chunks in document
order, the way noweb and org-babel do. The first one:

```rust
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}
``` <math-items>

and the second one, which the reader meets right where it belongs:

```rust
pub fn square(x: i32) -> i32 {
    x * x
}
``` <math-items>

== The binary

The binary uses the shared preamble again, and prints the results of both
functions:

```rust
<<crate-preamble>>

use lp_demo::math;

fn main() {
    <<print-results>>
}
``` #label("src/main.rs")

```rust
println!("add(2, 3) = {}", math::add(2, 3));
println!("square(5) = {}", math::square(5));
``` <print-results>

== Running the result

```sh
lp tangle examples/demo/literate.typ --out examples/demo/build
cargo run --quiet --manifest-path examples/demo/build/Cargo.toml
```

```
add(2, 3) = 5
square(5) = 25
```

== When it breaks

If that binary stops compiling, the error is reported against the *generated*
file — `src/main.rs:6:5: cannot find function ...`. `lp` records which document
line produced every generated line, so the diagnostic can be translated back:

```sh
cargo build --manifest-path examples/demo/build/Cargo.toml --message-format=short 2>&1 \
  | lp explain --out examples/demo/build
```

That is the difference between this and a preprocessor that only knows how to
dump text: the generated code stays accountable to the prose it came from.
