#import "../../lit/lp.typ": chunk, file, rule
#show: rule

#set page(width: 15cm, height: auto, margin: 2cm)
#set text(size: 10pt)

= A multi-file crate, written as one document

This document is a normal Typst file — `typst compile examples/demo/literate.typ`
renders it. It is also the only source of a small Rust crate: every `#file(...)`
declaration names a real file to write when you run

```sh
lp tangle examples/demo/literate.typ --out examples/demo/build
```

Text like this never reaches the generated code. `#chunk("name", …)` declares a
fragment and chunks pull each other in with `<<name>>`. The order is the reading
order: the three files first, as skeletons that name what they need, then each
piece in the section that explains it. A name is always used before it is
declared, and `lp` refuses a document where that is not true — so the structure
below is not a convention, it is the one the tool accepts.

== The manifest

The crate is its own workspace so the surrounding repository's `Cargo.toml`
does not claim it.

#file("Cargo.toml", ```toml
[package]
name = "lp-demo"
version = "0.0.0"
edition = "2024"

# `lp` output is standalone; keep it out of the parent workspace.
[workspace]
```)

== The library

Two thirds of the crate: a banner comment it shares with the binary, and one
module. Neither is spelled out here — the sections below do that, in the order a
reader wants them.

`` `<<math-items>>` `` sits inside a module, so its two chunks are indented by four
spaces on the way out:

#file("src/lib.rs", ```rust
<<crate-preamble>>

pub mod math {
    <<math-items>>
}
```)

== The binary

The entry point: the same banner, the library's module, and whatever `main`
prints.

#file("src/main.rs", ```rust
<<crate-preamble>>

use lp_demo::math;

fn main() {
    <<print-results>>
}
```)

== The shared preamble

Both crate roots want the same banner comment at the top. It is not something
`lp` injects: the tool writes exactly the chunks you give it, nothing else. This
is just a chunk that two different root chunks happen to pull in — the same text
in two files, written once:

#chunk("crate-preamble", ```rust
//! generated by lp from literate.typ — edit the document, not this file
```)

== The module body

The module has two functions, declared as two separate `#chunk("math-items", …)`
blocks. Tangling concatenates declarations sharing a name, in document order, the
way noweb and org-babel do. The first one:

#chunk("math-items", ```rust
pub fn add(a: i32, b: i32) -> i32 {
    a + b
}
```)

and the second one, which the reader meets right where it belongs:

#chunk("math-items", ```rust
pub fn square(x: i32) -> i32 {
    x * x
}
```)

== What `main` prints

#chunk("print-results", ```rust
println!("add(2, 3) = {}", math::add(2, 3));
println!("square(5) = {}", math::square(5));
```)

== Running the result

```sh
lp tangle examples/demo/literate.typ --out examples/demo/build
cargo run --quiet --manifest-path examples/demo/build/Cargo.toml
```

```
add(2, 3) = 5
square(5) = 25
```

== Who owns that directory

`examples/demo/build/.lpignore` declares it as ours: every file in there that no
chunk produces gets removed, and the ones listed in the file are left alone —
cargo's `target/` and `Cargo.lock`, the woven PDF, the PNGs. Delete a root chunk
here and its file follows, instead of lingering for `cargo` to compile.

The rule is simple: point `--out` at a directory and that whole directory is
`lp`'s. Every file in it must be either produced by a chunk or declared in an
`.lpignore`. Anything else is an error — `lp tangle` fails and names it — and the
two ways out are to declare it, or to delete it on purpose with
`lp unaccounted --delete`. `lp` never removes anything by itself.

== When it breaks

If that binary stops compiling, the error is reported against the *generated*
file — `src/main.rs:6:5: cannot find function ...`. `lp` records which chunk
produced every generated line, so the diagnostic can be translated back:

```sh
cargo build --manifest-path examples/demo/build/Cargo.toml --message-format=short 2>&1 \
  | lp explain --out examples/demo/build
```

That is the difference between this and a preprocessor that only knows how to
dump text: the generated code stays accountable to the prose it came from.
