//! The line map: which `.typ` line produced which line of which generated file.
//!
//! One map per directory, next to the files it describes: `out/.lpmap.json`
//! covers the files directly in `out/`, `out/src/.lpmap.json` covers the files
//! directly in `out/src/`. Progressive disclosure — a reader, person or agent,
//! opens the directory it cares about instead of one index of the whole tree; the
//! map travels with the files it explains; and a directory that stops producing
//! anything takes its map with it.

use std::collections::{BTreeMap, BTreeSet};
use std::path::{Path, PathBuf};

use ignore::WalkBuilder;
use serde::{Deserialize, Serialize};

use crate::diag::LpError;

pub const MAP_FILE: &str = ".lpmap.json";
const VERSION: u32 = 4;

#[derive(Debug, Serialize, Deserialize)]
pub struct LpMap {
    pub version: u32,
    /// Documents that produced the files listed here.
    pub docs: Vec<String>,
    /// Keyed by file name *within this directory*.
    pub files: BTreeMap<String, FileMap>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileMap {
    /// The source files this output's lines came from, in the order the line
    /// entries refer to them. Usually one; a document split across files, or a
    /// chunk defined in two of them, makes it more.
    pub sources: Vec<String>,
    pub lang: Option<String>,
    /// `[output line, line in sources[i], i]`, 1-based, in output order. The last
    /// two are `null` when the document built that line instead of writing it, so
    /// there is no line to point at.
    pub lines: Vec<(usize, Option<usize>, Option<usize>)>,
    /// Chunks that contributed lines to this file, in document order.
    pub chunks: Vec<ChunkEntry>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ChunkEntry {
    pub name: String,
    /// Where the chunk was written, when the source has a line for it.
    pub typ_line: Option<usize>,
    pub end_line: Option<usize>,
}

impl Default for LpMap {
    fn default() -> Self {
        Self {
            version: VERSION,
            docs: Vec::new(),
            files: BTreeMap::new(),
        }
    }
}

impl LpMap {
    pub fn is_empty(&self) -> bool {
        self.files.is_empty()
    }

    pub fn set_docs(&mut self, docs: impl IntoIterator<Item = String>) {
        self.docs = docs
            .into_iter()
            .collect::<BTreeSet<_>>()
            .into_iter()
            .collect();
    }

    /// Write only when the serialized map actually differs.
    ///
    /// The map depends on the *document* (line numbers, chunk names, boundaries),
    /// not just on the generated bytes: inserting a line of prose above a chunk
    /// shifts every mapping while leaving every output file identical. Comparing
    /// the whole map keeps it correct without handing editors and CI a file whose
    /// mtime moves on every pass.
    pub fn write_if_changed(&self, dir: &Path) -> Result<bool, LpError> {
        let (path, json) = self.serialize(dir)?;
        if std::fs::read_to_string(&path).ok().as_deref() == Some(json.as_str()) {
            return Ok(false);
        }
        std::fs::write(&path, json).map_err(|e| LpError::io(&path, e))?;
        Ok(true)
    }

    pub fn read(dir: &Path) -> Result<Self, LpError> {
        let path = dir.join(MAP_FILE);
        let text = std::fs::read_to_string(&path).map_err(|e| LpError::io(&path, e))?;
        serde_json::from_str(&text).map_err(|e| LpError::plain(format!("{}: {e}", path.display())))
    }

    /// Every map under `out`, paired with its directory relative to `out` (`""`
    /// for the output directory itself), in a stable order.
    pub fn read_all(out: &Path) -> Vec<(String, LpMap)> {
        if !out.exists() {
            return Vec::new();
        }

        let walker = WalkBuilder::new(out)
            .standard_filters(false)
            .hidden(false)
            .build();
        let mut found = Vec::new();
        for entry in walker.flatten() {
            if entry.file_name() != MAP_FILE {
                continue;
            }
            let Some(dir) = entry.path().parent() else {
                continue;
            };
            if let Ok(map) = Self::read(dir) {
                found.push((relative(out, dir), map));
            }
        }
        found.sort_by(|a, b| a.0.cmp(&b.0));
        found
    }

    fn serialize(&self, dir: &Path) -> Result<(PathBuf, String), LpError> {
        let path = dir.join(MAP_FILE);
        let json = serde_json::to_string_pretty(self)
            .map_err(|e| LpError::plain(format!("{}: {e}", path.display())))?;
        Ok((path, json + "\n"))
    }
}

impl FileMap {
    /// The source file a line entry points at, when the line has one.
    pub fn source(&self, entry: (usize, Option<usize>, Option<usize>)) -> Option<&str> {
        entry
            .2
            .and_then(|index| self.sources.get(index))
            .map(String::as_str)
    }

    /// Where did this output line come from? Falls back to the closest earlier
    /// line so blank lines and generated separators still report something.
    pub fn locate(&self, line: usize) -> Option<(usize, Option<usize>, Option<usize>)> {
        let exact = self.lines.iter().find(|entry| entry.0 == line);
        exact
            .or_else(|| self.lines.iter().rev().find(|entry| entry.0 < line))
            .copied()
    }

    pub fn chunk_at(&self, typ_line: usize) -> Option<&ChunkEntry> {
        self.chunks
            .iter()
            .rev()
            .find(|chunk| match (chunk.typ_line, chunk.end_line) {
                (Some(first), Some(last)) => first <= typ_line && typ_line <= last,
                _ => false,
            })
    }
}

/// Split an output path into `(directory, file name)`; the directory is `""` for
/// files directly in the output directory. Both use forward slashes.
pub fn split(rel: &str) -> (&str, &str) {
    match rel.rsplit_once('/') {
        Some((dir, name)) => (dir, name),
        None => ("", rel),
    }
}

pub fn join(dir: &str, name: &str) -> String {
    if dir.is_empty() {
        name.to_string()
    } else {
        format!("{dir}/{name}")
    }
}

/// Relative path with forward slashes.
pub fn relative(out: &Path, path: &Path) -> String {
    path.strip_prefix(out)
        .unwrap_or(path)
        .to_string_lossy()
        .replace('\\', "/")
}

/// Where did this file come from? `file` is a path as a toolchain reported it:
/// relative to the output directory, to the working directory, or absolute.
///
/// The map of the most specific directory wins; if two directories could equally
/// well claim the name, that is an error rather than a guess.
pub fn resolve<'a>(
    maps: &'a [(String, LpMap)],
    file: &str,
) -> Result<(&'a str, &'a str, &'a FileMap), LpError> {
    let normalized = file.trim_start_matches("./").replace('\\', "/");
    let (dir, name) = split(&normalized);

    let mut candidates: Vec<(&str, &str, &FileMap)> = Vec::new();
    for (map_dir, map) in maps {
        let Some((key, entry)) = map.files.get_key_value(name) else {
            continue;
        };
        let in_scope = dir.is_empty()
            || map_dir.is_empty()
            || dir == map_dir
            || dir.ends_with(&format!("/{map_dir}"));
        if in_scope {
            candidates.push((map_dir.as_str(), key.as_str(), entry));
        }
    }

    candidates.sort_by_key(|(map_dir, _, _)| std::cmp::Reverse(map_dir.len()));
    let Some(best) = candidates.first() else {
        let known = maps
            .iter()
            .map(|(dir, _)| if dir.is_empty() { "." } else { dir.as_str() })
            .collect::<Vec<_>>()
            .join(", ");
        return Err(
            LpError::plain(format!("{file}: not in any line map")).with_help(format!(
                "maps found in: {}",
                if known.is_empty() {
                    "(none)".into()
                } else {
                    known
                }
            )),
        );
    };

    if candidates
        .get(1)
        .is_some_and(|(map_dir, _, _)| map_dir.len() == best.0.len())
    {
        let all = candidates
            .iter()
            .map(|(dir, name, _)| join(dir, name))
            .collect::<Vec<_>>()
            .join(", ");
        return Err(LpError::plain(format!("{file}: which line map?"))
            .with_help(format!("candidates: {all}; name the directory")));
    }

    Ok(*best)
}
